# Generated by Django 5.2.5 on 2025-10-15 18:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Convenio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'neurocare.tb_convenio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FaixaEtaria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'neurocare.tb_faixa_etaria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome_completo', models.CharField(max_length=255)),
                ('data_nascimento', models.DateField()),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('rg', models.CharField(blank=True, max_length=20, null=True)),
                ('genero', models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino'), ('Outro', 'Outro'), ('Não Informar', 'Não Informar')], max_length=50)),
                ('estado_civil', models.CharField(choices=[('Solteiro', 'Solteiro'), ('Casado', 'Casado'), ('Divorciado', 'Divorciado'), ('Viúvo', 'Viúvo'), ('União Estável', 'União Estável')], max_length=50)),
                ('profissao', models.CharField(blank=True, max_length=100, null=True)),
                ('telefone_principal', models.CharField(max_length=20)),
                ('telefone_secundario', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('endereco_rua', models.CharField(blank=True, max_length=255, null=True)),
                ('endereco_numero', models.CharField(blank=True, max_length=50, null=True)),
                ('endereco_complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('endereco_bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('endereco_cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('endereco_estado', models.CharField(blank=True, max_length=50, null=True)),
                ('endereco_cep', models.CharField(blank=True, max_length=10, null=True)),
                ('quem_encaminhou', models.CharField(blank=True, max_length=255, null=True)),
                ('motivo_encaminhamento', models.TextField(blank=True, null=True)),
                ('numero_carteirinha_convenio', models.CharField(blank=True, max_length=100, null=True)),
                ('validade_carteirinha_convenio', models.DateField(blank=True, null=True)),
                ('status_paciente', models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo'), ('Alta', 'Alta'), ('Em Espera', 'Em Espera')], max_length=50)),
                ('observacoes_gerais', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'neurocare.tb_paciente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome_completo', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('login', models.CharField(max_length=100, unique=True)),
                ('senha_hash', models.CharField(max_length=255)),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'neurocare.tb_usuario',
                'managed': False,
            },
        ),
    ]
